# Generated by Django 5.0 on 2024-01-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter_app', '0002_alter_calorie_counter_model_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorie_counter_model',
            name='total_calorie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
