# Generated by Django 5.0 on 2024-01-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter_app', '0003_calorie_counter_model_total_calorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorie_counter_model',
            name='total_calorie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
