# Generated by Django 5.0 on 2024-01-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter_app', '0004_alter_calorie_counter_model_total_calorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iteam_Calorie_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('calorie', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
