# Generated by Django 5.0 on 2024-01-17 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter_app', '0005_iteam_calorie_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteam_calorie_model',
            name='date',
        ),
        migrations.AddField(
            model_name='iteam_calorie_model',
            name='today_date',
            field=models.DateField(default=datetime.date(2024, 1, 17)),
        ),
    ]
