# Generated by Django 5.0 on 2024-01-17 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter_app', '0008_date_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteam_calorie_model',
            name='today_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_date', to='calorie_counter_app.date_model'),
        ),
    ]
