# Generated by Django 5.0 on 2024-01-17 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter_app', '0009_alter_iteam_calorie_model_today_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iteam_calorie_model',
            old_name='today_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='date_model',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
