# Generated by Django 5.0 on 2024-01-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter_app', '0010_rename_today_date_iteam_calorie_model_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_model',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
