# Generated by Django 5.0 on 2024-01-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter_app', '0011_alter_date_model_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='date_model',
            name='today_total_calorie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
