# Generated by Django 5.0 on 2024-01-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter_app', '0013_date_model_need_calorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_model',
            name='need_calorie',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='date_model',
            name='today_total_calorie',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
